version: '3'
services:
 traefik:
  image: "traefik:v2.5"
  container_name: "traefik"
  command:
    #- "--log.level=DEBUG"
    - "--api.insecure=true"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    - "--entrypoints.web.address=:80"
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"

 radarr:
  container_name: radarr
  restart: unless-stopped
  ports:
   - 7878:7878
  volumes:
   - /home/user/radarr:/config
   - /home/user/downloads:/downloads
   - /home/user/downloads:/movies
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Europe/Berlin
  image: linuxserver/radarr
  labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/radarr`)"
      - "traefik.http.routers.whoami.entrypoints=web"

 sonarr:
  container_name: sonarr
  restart: unless-stopped
  ports:
   - 8989:8989
  volumes:
   - /home/user/sonarr:/config
   - /home/user/downloads:/downloads
   - /home/user/downloads:/tv
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Europe/Berlin
  image: linuxserver/sonarr
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.whoami.rule=PathPrefix(`/sonarr`)"
    - "traefik.http.routers.whoami.entrypoints=web"

 lidarr:
  container_name: lidarr
  restart: unless-stopped
  ports:
   - 8686:8686
  volumes:
   - /home/user/lidarr:/config
   - /home/user/downloads:/downloads
   - /home/user/downloads:/music
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Europe/Berlin
  image: linuxserver/lidarr
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.whoami.rule=PathPrefix(`/lidarr`)"
    - "traefik.http.routers.whoami.entrypoints=web"

 jackett:
  container_name: jackett
  restart: unless-stopped
  ports:
   - 9117:9117
  volumes:
   - /home/user/jackett:/config
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Europe/Berlin
  image: linuxserver/jackett
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.whoami.rule=PathPrefix(`/jackett`)"
    - "traefik.http.routers.whoami.entrypoints=web"

 lazylibrarian:
  container_name: lazylibrarian
  restart: unless-stopped
  ports:
    - 5299:5299
  volumes:
    - /home/user/lazylib:/config
    - /home/user/downloads/:/downloads
    - /home/user/downloads:/books
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Berlin
    - DOCKER_MODS=linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
  image: lscr.io/linuxserver/lazylibrarian
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.whoami.rule=PathPrefix(`/lazylib`)"
    - "traefik.http.routers.whoami.entrypoints=web"

 transmission:
  container_name: transmission
  restart: unless-stopped
  ports:
    - 9091:9091
    #- 51413:51413
    #- 51413:51413/udp
  volumes:
    - /home/user/transmission:/config
    - /home/user/downloads:/downloads
    - /home/user/downloads:/watch
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Berlin
    #- TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    #- USER=username #optional
    #- PASS=password #optional
    #- WHITELIST=iplist #optional
    #- HOST_WHITELIST=dnsnane list #optional
  image: lscr.io/linuxserver/transmission
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.whoami.rule=PathPrefix(`/trans`)"
    - "traefik.http.routers.whoami.entrypoints=web"

 vpn:
  container_name: vpn
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  dns:
    - 103.86.96.100
    - 103.86.99.100
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ovpn-data:/app/ovpn/config
  environment:
    - USERNAME=${USERNAME}
    - PASSWORD=${PASSWORD}
    - LOCAL_NETWORK=192.168.178.0/24
    - COUNTRY=DE
  networks:
    - default
  ports:
    - 8118:8118
  restart: unless-stopped
  image: jeroenslot/nordvpn-proxy:latest

volumes:
  ovpn-data: