version: '3'
services:
 radarr:
  container_name: radarr
  restart: unless-stopped
  ports:
   - 7878:7878
  volumes:
   - /home/user/radarr:/config
   - /home/user/downloads:/downloads
   - /home/user/downloads:/movies
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Europe/Berlin
  image: linuxserver/radarr

 sonarr:
  container_name: sonarr
  restart: unless-stopped
  ports:
   - 8989:8989
  volumes:
   - /home/user/sonarr:/config
   - /home/user/downloads:/downloads
   - /home/user/downloads:/tv
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Europe/Berlin
  image: linuxserver/sonarr

 lidarr:
  container_name: lidarr
  restart: unless-stopped
  ports:
   - 8686:8686
  volumes:
   - /home/user/lidarr:/config
   - /home/user/downloads:/downloads
   - /home/user/downloads:/music
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Europe/Berlin
  image: linuxserver/lidarr

 jackett:
  container_name: jackett
  restart: unless-stopped
  ports:
   - 9117:9117
  volumes:
   - /home/user/jackett:/config
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Europe/Berlin
  image: linuxserver/jackett

 vpn:
  container_name: vpn
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  dns:
    - 103.86.96.100
    - 103.86.99.100
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ovpn-data:/app/ovpn/config
  environment:
    - USERNAME=${USERNAME}
    - PASSWORD=${PASSWORD}
    - LOCAL_NETWORK=192.168.178.0/24
    - COUNTRY=DE
  networks:
    - default
  ports:
    - 8118:8118
  restart: always
  image: jeroenslot/nordvpn-proxy:latest

volumes:
  ovpn-data: