version: '3.8'
services:
 traefik:
  container_name: traefik
  restart: unless-stopped
  #ports:
    # - "80:80"
    #- "8080:8080"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
  command:
    - "--log.level=DEBUG"
    - "--api.insecure=true"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    - "--entrypoints.web.address=:80"
  image: "traefik:v2.5"
  network_mode: "service:vpn"
  logging:
   driver: json-file
   options:
    max-size: 1m

 radarr:
  container_name: radarr
  restart: unless-stopped
  #ports:
   #- 7878:7878
  volumes:
   - /home/user/radarr:/config
   - /home/user/downloads:/downloads
   - /home/user/downloads:/movies
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Europe/Berlin
  image: linuxserver/radarr
  network_mode: "service:vpn"
  labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.docker`)"
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
  logging:
   driver: json-file
   options:
    max-size: 1m

 sonarr:
  container_name: sonarr
  restart: unless-stopped
  #ports:
   #- 8989:8989
  volumes:
   - /home/user/sonarr:/config
   - /home/user/downloads:/downloads
   - /home/user/downloads:/tv
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Europe/Berlin
  image: linuxserver/sonarr
  network_mode: "service:vpn"
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.sonarr.rule=Host(`sonarr.docker`)"
    - "traefik.http.routers.sonarr.entrypoints=web"
    - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
  logging:
   driver: json-file
   options:
    max-size: 1m

 lidarr:
  container_name: lidarr
  restart: unless-stopped
  #ports:
   #- 8686:8686
  volumes:
   - /home/user/lidarr:/config
   - /home/user/downloads:/downloads
   - /home/user/downloads:/music
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Europe/Berlin
  image: linuxserver/lidarr
  network_mode: "service:vpn"
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.lidarr.rule=Host(`lidarr.docker`)"
    - "traefik.http.routers.lidarr.entrypoints=web"
    - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
  logging:
   driver: json-file
   options:
    max-size: 1m

 readarr:
  container_name: readarr
  restart: unless-stopped
  #ports:
   #- 8787:8787
  volumes:
    - /home/user/readarr:/config
    - /home/user/downloads:/downloads
    - /home/user/downloads:/books
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Berlin
  image: linuxserver/readarr:nightly
  network_mode: "service:vpn"
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.readarr.rule=Host(`readarr.docker`)"
    - "traefik.http.routers.readarr.entrypoints=web"
    - "traefik.http.services.readarr.loadbalancer.server.port=8787"
  logging:
   driver: json-file
   options:
    max-size: 1m

 prowlarr:
  container_name: prowlarr
  restart: unless-stopped
  #ports:
   #- 9696:9696
  volumes:
    - /home/user/prowlarr:/config
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Berlin
  image: ghcr.io/linuxserver/prowlarr:develop
  network_mode: "service:vpn"
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.docker`)"
    - "traefik.http.routers.prowlarr.entrypoints=web"
    - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
  logging:
   driver: json-file
   options:
    max-size: 1m

 jackett:
  container_name: jackett
  restart: unless-stopped
  #ports:
   #- 9117:9117
  volumes:
   - /home/user/jackett:/config
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Europe/Berlin
  image: linuxserver/jackett
  network_mode: "service:vpn"
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.jackett.rule=Host(`jackett.docker`)"
    - "traefik.http.routers.jackett.entrypoints=web"
    - "traefik.http.services.jackett.loadbalancer.server.port=9117"
  logging:
   driver: json-file
   options:
    max-size: 1m

 lazylibrarian:
  container_name: lazylibrarian
  restart: unless-stopped
  #ports:
    #- 5299:5299
  volumes:
    - /home/user/lazylib:/config
    - /home/user/downloads/:/downloads
    - /home/user/downloads:/books
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Berlin
    - DOCKER_MODS=linuxserver/mods:lazylibrarian-ffmpeg #optional
  image: linuxserver/lazylibrarian
  network_mode: "service:vpn"
  labels:
  - "traefik.enable=true"
  - "traefik.http.routers.lazylib.rule=Host(`lazylib.docker`)"
  - "traefik.http.routers.lazylib.entrypoints=web"
  - "traefik.http.services.lazylib.loadbalancer.server.port=5299"
  logging:
   driver: json-file
   options:
    max-size: 1m

 transmission:
  container_name: transmission
  restart: unless-stopped
  #ports:
    #- 9091:9091
    #- 51413:51413
    #- 51413:51413/udp
  volumes:
    - /home/user/transmission:/config
    - /home/user/downloads:/downloads
    - /home/user/downloads:/watch
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Berlin
    #- TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    #- USER=username #optional
    #- PASS=password #optional
    #- WHITELIST=iplist #optional
    #- HOST_WHITELIST=dnsnane list #optional
  image: lscr.io/linuxserver/transmission
  network_mode: "service:vpn"
  labels:
  - "traefik.enable=true"
  - "traefik.http.routers.trans.rule=Host(`trans.docker`)"
  - "traefik.http.routers.trans.entrypoints=web"
  - "traefik.http.services.trans.loadbalancer.server.port=9091"
  logging:
   driver: json-file
   options:
    max-size: 1m

 flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Berlin
    restart: unless-stopped
    network_mode: "service:vpn"
    logging:
     driver: json-file
     options:
      max-size: 1m

 unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - /home/user/downloads:/data/downloads
    restart: always
    user: 1000:1000
    # What you see below are defaults. You only need to include things you change.
    environment:
      - TZ=Europe/Berlin
      # General config
      - UN_DEBUG=false
      - UN_LOG_FILE=
      - UN_LOG_FILES=10
      - UN_LOG_FILE_MB=10
      - UN_INTERVAL=2m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=0755
      # Sonarr Config
      - UN_SONARR_0_URL=http://172.21.0.3:8989
      - UN_SONARR_0_API_KEY=
      - UN_SONARR_0_PATHS_0=/data/downloads
      - UN_SONARR_0_PROTOCOLS=torrent
      - UN_SONARR_0_TIMEOUT=10s
      - UN_SONARR_0_DELETE_ORIG=true
      - UN_SONARR_0_DELETE_DELAY=5m
      # Radarr Config
      - UN_RADARR_0_URL=http://172.21.0.3:7878
      - UN_RADARR_0_API_KEY=
      - UN_RADARR_0_PATHS_0=/data/downloads
      - UN_RADARR_0_PROTOCOLS=torrent
      - UN_RADARR_0_TIMEOUT=10s
      - UN_RADARR_0_DELETE_ORIG=true
      - UN_RADARR_0_DELETE_DELAY=5m
      # Lidarr Config
      - UN_LIDARR_0_URL=http://172.21.0.3:8686
      - UN_LIDARR_0_API_KEY=
      - UN_LIDARR_0_PATHS_0=/data/downloads
      - UN_LIDARR_0_PROTOCOLS=torrent
      - UN_LIDARR_0_TIMEOUT=10s
      - UN_LIDARR_0_DELETE_ORIG=true
      - UN_LIDARR_0_DELETE_DELAY=5m
      # Readarr Config
      - UN_READARR_0_URL=http://172.21.0.3:8787
      - UN_READARR_0_API_KEY=
      - UN_READARR_0_PATHS_0=/data/downloads
      - UN_READARR_0_PROTOCOLS=torrent
      - UN_READARR_0_TIMEOUT=10s
      - UN_READARR_0_DELETE_ORIG=true
      - UN_READARR_0_DELETE_DELAY=5m
      # Folder Config
      - UN_FOLDER_0_PATH=
      - UN_FOLDER_0_EXTRACT_PATH=
      - UN_FOLDER_0_DELETE_AFTER=10m
      - UN_FOLDER_0_DELETE_ORIGINAL=false
      - UN_FOLDER_0_DELETE_FILES=false
      - UN_FOLDER_0_MOVE_BACK=false
      # Webhook Config
      - UN_WEBHOOK_0_URL=
      - UN_WEBHOOK_0_NAME=
      - UN_WEBHOOK_0_NICKNAME=Unpackerr
      - UN_WEBHOOK_0_CHANNEL=
      - UN_WEBHOOK_0_TIMEOUT=5
      - UN_WEBHOOK_0_SILENT=true
      - UN_WEBHOOK_0_IGNORE_SSL=false
      - UN_WEBHOOK_0_EXCLUDE=[]
      - UN_WEBHOOK_0_EVENTS=[0]
      - UN_WEBHOOK_0_TEMPLATE_PATH=
      - UN_WEBHOOK_0_CONTENT_TYPE=application/json
    security_opt:
      - no-new-privileges:true

 vpn:
  container_name: vpn
  restart: unless-stopped
  ports:
    - 8118:8118 # privoxy
    - 9091:9091 # transmission
    - 5299:5299 # lazylib
    - 9117:9117 # jackett
    - 8686:8686 # lidarr
    - 8989:8989 # sonarr
    - 7878:7878 # radarr
    - 9696:9696 # prowlarr
    - 8787:8787 # readarr
    - 8191:8191 # flaresolverr
    - 80:80 # traefik
    - 8080:8080 # traefik dashboard
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  dns:
    - 103.86.96.100
    - 103.86.99.100
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ovpn-data:/app/ovpn/config
  environment:
    - USERNAME=${USERNAME}
    - PASSWORD=${PASSWORD}
    - LOCAL_NETWORK=192.168.178.0/24
    - COUNTRY=DE
  networks:
    - default
  image: jeroenslot/nordvpn-proxy:latest
  labels:
  - "traefik.enable=true"
  - "traefik.http.routers.dashboard.rule=Host(`traefik.docker`)"
  - "traefik.http.routers.dashboard.entrypoints=web"
  - "traefik.http.routers.dashboard.service=dashboard@internal"
  - "traefik.http.routers.api.rule=Host(`traefik.docker`) && PathPrefix(`/api`)"
  - "traefik.http.routers.api.entrypoints=web"
  - "traefik.http.routers.api.service=api@internal"
  logging:
   driver: json-file
   options:
    max-size: 1m

 dns:
  container_name: dns
  restart: unless-stopped
  ports:
    - 53:53/udp
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
  environment:
    - DNS_DOMAIN=docker
    - HOSTMACHINE_IP=127.0.0.1
    - EXTRA_HOSTS="" # optional
  image: ruudud/devdns
  logging:
   driver: json-file
   options:
    max-size: 1m

volumes:
  ovpn-data:
